version: "3"
services:

  #Influx Database
  influxdb:
    restart: unless-stopped
    image: echteler/influxdb:arm32v7
    environment:
      INFLUXDB_DB: db1
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: 0815
      INFLUXDB_USER: influx
      INFLUXDB_USER_PASSWORD: database
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089"
    volumes:
      - influxData:/var/lib/influxdb
    networks: 
      - edge

  #Nodered to Wire all up
  nodered: 
    restart: unless-stopped
    image: echteler/nodered:arm32v7
    ports: 
      - "1880:1880"
    volumes:
      - noderedData:/data
    networks:
      - edge

  #Grafana to do easy metrics analytics
  grafana:
    restart: unless-stopped
    image: echteler/grafana:arm32v7
    ports:
      - "3000:3000"
    volumes: 
      - grafanaData:/var/lib/grafana
    networks:
      - edge

  #Mosquitto as MQTT Broker
  mosquitto:
    restart: unless-stopped
    image: echteler/mosquitto:arm32v7
    ports: 
      - "1883:1883"
      - "9001:9001"
    volumes: 
      - mosquittoLog:/mosquitto/log
      - mosquittoData:/mosquitto/data
    networks:
      - edge

  #Portainer for container mgmt. 
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - edge

  #Ftp Server    
  ftpserver:
    image: echteler/ftpserver:arm32v7
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      DEFAULT_USR: balluff
      DEFAULT_PWD: balluff
    volumes:
      - ftpdata:/home/ftpuser
      - ftpconfig:/etc/pureftpd
    restart: unless-stopped
    networks:
      - edge

  #Webserver as Entry Point
  webserver:
    image: echteler/apachewebserver:arm32v7
    restart: unless-stopped
    ports:
      - "80:80"
    volumes: 
      - webserverdata:/usr/local/apache2/htdocs/
    networks:
      - edge 
  
  #Kapacitor 
  kapacitor:
    image: echteler/kapacitor:arm32v7
    restart: unless-stopped
    ports:
      - "9092:9092"
    volumes: 
      - kapacitordata:/var/lib/kapacitor
    networks:
      - edge 
  
  #Chronograf: 
  chronograf:
    image: echteler/chronograf:arm32v7
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes: 
      - chronografdata:/var/lib/chronograf
    networks:
      - edge 
  
  #Telegraf
  telegraf:
    image: echteler/telegraf:arm32v7
    restart: unless-stopped
    ports:
      - "8125:8125"
      - "8092:8092"
      - "8094:8094"
    networks:
      - edge 


#Create internal link network for Containers
networks:
  edge:

#Create Volumes for persistent Storage
volumes:
  influxData:
  noderedData:
  grafanaData:
  mosquittoLog:
  mosquittoData:
  portainer_data:
  ftpdata:
  ftpconfig:
  webserverdata:
  kapacitordata:
  chronografdata:

#  - mosquittoConf:/mosquitto/config/mosquitto.conf    
# mosquittoConf: